name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/checkout@v4
        with:
          repository: darknao/zmk
          ref: darknao/rgb-dts
          path: zmk
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-venv git cmake ninja-build gperf ccache dfu-util device-tree-compiler wget
          sudo apt install -y gcc-multilib g++-multilib libc6-dev-i386
      - name: Install Python dependencies
        run: |
          python3 -m pip install --user -U west
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Initialize west workspace
        run: |
          cd zmk
          west init -l app
          west update
          cd ..
      - name: Install Zephyr SDK
        run: |
          cd ~
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.8/zephyr-sdk-0.16.8_linux-x86_64.tar.xz
          tar xf zephyr-sdk-0.16.8_linux-x86_64.tar.xz
          cd zephyr-sdk-0.16.8
          ./setup.sh -t all -h -c
      - name: Build Glove80 firmware (left half)
        run: |
          cd zmk
          west build -s app -d build/left -b glove80_lh -- -DZMK_CONFIG="$GITHUB_WORKSPACE/config"
      - name: Build Glove80 firmware (right half) 
        run: |
          cd zmk
          west build -s app -d build/right -b glove80_rh -- -DZMK_CONFIG="$GITHUB_WORKSPACE/config"
      - name: Copy firmware files
        run: |
          mkdir -p firmware
          cp zmk/build/left/zephyr/zmk.uf2 firmware/glove80_left.uf2
          cp zmk/build/right/zephyr/zmk.uf2 firmware/glove80_right.uf2
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: glove80-firmware
          path: firmware/